[workspace]
members = [
	"lang",
	"lang-impl",
	"lang-quote",
]

[patch.crates-io]
glsl-lang = { path = "lang" }
glsl-lang-impl = { path = "lang-impl" }
glsl-lang-quote = { path = "lang-quote" }

[profile.dev.build-override]
opt-level = 2

[profile.release.build-override]
opt-level = 2
