ignore_merge_commits = true
branch_whitelist = [
  "master",
]
pre_bump_hooks = [
  "./ci/bumpver.sh {{version}}",
  "git add */Cargo.toml",
]
post_bump_hooks = [
  "git commit --amend --no-edit -m \"chore(version): v{{version}} [skip ci]\"",
  "git push",
  "git push origin v{{version}}",
  "./ci/release.sh",
]
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "Vincent Tavernier", username = "vtavernier" }
]

[bump_profiles]
