[package]
name = "lang-util"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
lang-util-derive = "=0.1.0"
parse-display = { version = "0.4", default-features = false, features = ["std"] }
