[package]
name = "lang-util-derive"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.12"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
