[package]
name = "glsl-lang"
version = "0.2.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "GLSL 4.6 language LALR parser and AST"
homepage = "https://github.com/vtavernier/glsl-lang"
documentation = "https://docs.rs/glsl-lang/"
repository = "https://github.com/vtavernier/glsl-lang"
readme = "README.md"
keywords = ["glsl", "language", "parser", "ast"]
categories = ["parser-implementations", "rendering"]

[dependencies]
lalrpop-util = { version = "0.19", default-features = false, features = ["std"] }
lazy_static = "1.4"
logos = { version = "0.12", optional = true }
thiserror = "1.0"

lang-util = { version = "0.2.0", features = ["lalrpop"] }
glsl-lang-pp = { version = "0.2.0", optional = true }
encoding_rs = { version = "0.8", optional = true }
smol_str = "0.1"

rserde = { version = "1.0", optional = true, features = ["derive"], package = "serde" }
text-size = "1.1"

[build-dependencies]
lalrpop = "0.19"

[dev-dependencies]
criterion = "0.3"
expect-test = "1.1"
glsl = "6"
glsl-lang-pp = "0.2.0"

[[test]]
name = "pos_error"
required-features = ["lexer-v2"]

[[bench]]
name = "glsl"
harness = false

[features]
# Default: only parse full translation units
default = ["lexer-v1"]

lexer = []
lexer-v1 = ["logos", "lexer"]
lexer-v2 = ["glsl-lang-pp", "encoding_rs", "lexer"]

# Additional sub-parsers. Increases compilation time.
parser-expr = []
parser-statement = []

# AST Serialization
serde = ["rserde", "lang-util/serde", "smol_str/serde"]
