[package]
name = "glsl-lang"
version = "0.1.1"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "GLSL 4.6 language LALR parser and AST"
homepage = "https://github.com/vtavernier/glsl-lang"
documentation = "https://docs.rs/glsl-lang/"
repository = "https://github.com/vtavernier/glsl-lang"
readme = "README.md"
keywords = ["glsl", "language", "parser", "ast"]
categories = ["parser-implementations", "rendering"]

[dependencies]
lalrpop-util = { version = "0.19", default-features = false, features = ["std"] }
lazy_static = "1.4"
logos = "0.12"
parse-display = { version = "0.4", default-features = false, features = ["std"] }
thiserror = "1.0"

lang-util = "0.1.1"
smol_str = "0.1"

[build-dependencies]
lalrpop = "0.19"

[dev-dependencies]
criterion = "0.3"
expect-test = "1.1"
glsl = "6"

[[bench]]
name = "glsl"
harness = false

[features]
# Default: only parse full translation units
default = []

# Additional sub-parsers. Increases compilation time.
parser-expr = []
parser-preprocessor = []
parser-statement = []
