[package]
name = "glsl-lang"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
glsl-lang-impl = "0.1.0"
logos = "0.12.0"
thiserror = "1.0.23"
lalrpop-util = "0.19.4"
lazy_static = "1.4.0"

[build-dependencies]
lalrpop = "0.19.4"

[dev-dependencies]
expect-test = "1.1.0"
