[package]
name = "glsl-lang-lexer"
version = "0.2.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "GLSL language lexers"
homepage = "https://github.com/vtavernier/glsl-lang"
documentation = "https://docs.rs/glsl-lang-lexer/"
repository = "https://github.com/vtavernier/glsl-lang"
readme = "README.md"
keywords = ["glsl", "language", "parser"]
categories = ["parser-implementations", "rendering"]

[dependencies]
glsl-lang-types = "0.2.0"
lang-util = "0.2.0"

thiserror = "1.0"

rserde = { version = "1.0", optional = true, features = ["derive"], package = "serde" }

# v1 lexer dependencies
logos = { version = "0.12", optional = true }

# v2 lexer dependencies
glsl-lang-pp = { version = "0.2.0", optional = true }
lalrpop-util = { version = "0.19.6", default-features = false, optional = true }

[features]
default = []
v1 = ["logos", "lalrpop"]
v2 = ["glsl-lang-pp", "lalrpop"]
lalrpop = ["lang-util/lalrpop", "lalrpop-util"]

# AST Serialization
serde = ["rserde", "glsl-lang-types/serde"]
