[package]
name = "glsl-lang-quote"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
glsl-lang = "0.1"
proc-macro2 = "1"
quote = "1"
