name: build

on: push

jobs:
  test:
    name: Test crate

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Run lib tests
        run: |
          set -e
          cargo test --lib

      - name: Run lib tests with serde
        run: |
          set -e
          cargo test --workspace --lib --features serde

      - name: Run lib tests with the three lexers
        run: |
          set -e
          cargo test -p glsl-lang --lib --features lexer-v1
          cargo test -p glsl-lang --lib --features lexer-v2-min
          cargo test -p glsl-lang --lib --features lexer-v2-full

      - name: Generate test driver
        run: cargo xtask gen-tests

      - name: Run glslang tests
        run: |
          set -e
          cargo test -p glsl-lang-pp --test glslang --features full
          cargo test -p glsl-lang --test glslang --no-default-features --features lexer-v1
          cargo test -p glsl-lang --test glslang --no-default-features --features lexer-v2-min
          cargo test -p glsl-lang --test glslang --no-default-features --features lexer-v2-full

      - name: Run glsl-lang-quote tests
        run: |
          cargo test -p glsl-lang-quote

# vim: ft=yaml:ts=2:sw=2:et
