name: build

on: push

jobs:
  test:
    name: Test crate

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Run tests
        run: |
          set -e
          cargo test
          cargo test -p lang-util --lib --features serde
          cargo test -p glsl-lang --lib --features serde

# vim: ft=yaml:ts=2:sw=2:et
